#pragma checksum "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "556642273f543793f972f34b8339c28f5b3a0dc0"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_BookService), @"mvc.1.0.view", @"/Views/Home/BookService.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland.viewmodel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"556642273f543793f972f34b8339c28f5b3a0dc0", @"/Views/Home/BookService.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"7058251e67477ed81f1fbef7512c03f3605d1a08", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_BookService : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Helperland.viewmodel.BookServiceViewModel>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "tel", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("form-control"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("placeholder", new global::Microsoft.AspNetCore.Html.HtmlString("Postal code"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("postcode_form"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("bathsec"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "CheckPostalCode", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "UserBookService", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "text", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("service_date"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("form-control date_field"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("onfocus", new global::Microsoft.AspNetCore.Html.HtmlString("(this.type=\'date\')"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("onblur", new global::Microsoft.AspNetCore.Html.HtmlString("(this.type=\'text\')"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("placeholder", new global::Microsoft.AspNetCore.Html.HtmlString("01/01/1111"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_13 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("service_time"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_14 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "time", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_15 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("placeholder", new global::Microsoft.AspNetCore.Html.HtmlString("00:00"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_16 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "3", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_17 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "4", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_18 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "5", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_19 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("value", "6", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_20 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("basic_time"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_21 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("form-select bed-option"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_22 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "checkbox", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_23 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("extra_s_check_1"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_24 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("extra_s_check_2"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_25 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("extra_s_check_3"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_26 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("extra_s_check_4"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_27 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("extra_s_check_5"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_28 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("comments"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_29 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("rows", new global::Microsoft.AspNetCore.Html.HtmlString("4"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_30 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("pets"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_31 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("check_box"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_32 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("hidden_field"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_33 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "hidden", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_34 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("terms-book"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_35 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "addServiceInfo", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.TextAreaTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_TextAreaTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line 3 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
  
    ViewData["Title"] = "BookService";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"
<!--Banner section-->
<section>
    <img src=""/assets/calculator-banner.png"" class=""img-fluid"" alt=""bookservice-banner"">
</section>
<section class=""faq-details new-container"">
    <div class=""container"">
        <div class=""mg-bottom"">
            <div class=""row justify-content-center"">
                <div class=""col-lg-8"">
                    <div class="" text-center "">
                        <h2 class=""content-title"">Set up your cleaning service</h2>
                    </div>
                </div>
            </div>
            <div class=""d-flex justify-content-center"">
                <div class=""line1""></div>
                <img src=""/assets/forma-1-copy-5.png"" style=""width: 24px;
                    height: 25px;
                    margin-top: 14px;"">
                <div class=""line2""></div>
            </div>
        </div>
        <div class=""row"">
            <div class=""col-lg-8"">
                <div class=""accordion-book"">
                    <ul class=""nav nav-t");
            WriteLiteral(@"abs nav-justified"">
                        <li class=""nav-item col-lg-3 col-md-3 col-sm-6"">
                            <button data-bs-target=""tab1"" class=""nav-link active active_tab col-step-1"" type=""button""
                                    aria-selected=""true"" id=""setup1"">
                                <img id=""step_1_img"" src=""/assets/setup-service.png""><div class=""btn_text"">Setup Service</div>
                            </button>
                        </li>
                        <li class=""nav-item col-lg-3 col-md-3 col-sm-6"">
                            <button data-bs-target=""tab2""class=""nav-link  col-step-2"" type=""button""
                                    aria-selected=""false"" id=""setup2"">
                                <img id=""step_2_img"" src=""/assets/schedule-plan 2.png""><div class=""btn_text""> Schedule Plan</div>
                            </button>
                        </li>
                        <li class=""nav-item col-lg-3 col-md-3 col-sm-6"">
                   ");
            WriteLiteral(@"         <button data-bs-target=""tab3"" class=""nav-link col-step-3"" type=""button""
                                    aria-selected=""false"" id=""setup3"">
                                <img id=""step_3_img"" src=""/assets/user-details 2.png""><div class=""btn_text""> Your Details</div>
                            </button>
                        </li>
                        <li class=""nav-item col-lg-3 col-md-3 col-sm-6"">
                            <button data-bs-target=""tab4"" class=""nav-link col-step-4"" type=""button""
                                    aria-selected=""false"" id=""setup4"">
                                <img id=""step_4_img"" src=""/assets/payment 2.png""><div class=""btn_text"">Make Payment</div>
                            </button>
                        </li>
                    </ul>
                    
                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc019376", async() => {
                WriteLiteral(@"
                        <div class=""ss_step_1"">
                            <p class=""fw-bold"">Enter Your Postal Code: </p>
                            <div class=""bed-row"">
                                <div class=""postcode"">
                                    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "556642273f543793f972f34b8339c28f5b3a0dc019911", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 65 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.zipCodeViewModel.zipcode);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_0.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                BeginWriteTagHelperAttribute();
                __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
                __tagHelperExecutionContext.AddHtmlAttribute("required", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                </div>
                                <div class=""bt book"">
                                    <button type=""submit"" class=""c_sub_btn postal_check_btn""><h3>Check Availability</h3></button>
                                    <!-- <button type=""submit"" class=""continueBtn""><h3>Check Availability</h3></button> -->
                                </div>
                            </div>
                        </div>
                    ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_4);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Action = (string)__tagHelperAttribute_5.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_5);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Controller = (string)__tagHelperAttribute_6.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n\r\n                    ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc024183", async() => {
                WriteLiteral(@"
                        <div class=""fade ss_step_2"">
                            <div class=""bed-row1 bathsec"">
                                <div class=""left-part"">
                                    <p class=""fw-bold"">When do you need the cleaner?</p>
                                    <div class=""bed-row"">
                                        <div class=""col-sm-7 cal-dt"">
                                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc024888", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 82 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.servicestartdate);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_7.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_7);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_8);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_9);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_10);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_11);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_12);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                            <span class=""date-button"">
                                                <img src=""/assets/admin-calendar-blue.png"">
                                            </span>
                                        </div>
                                        <div class=""col-sm-5 clock-container"">
                                            ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "556642273f543793f972f34b8339c28f5b3a0dc027456", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 88 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.servicestrarttime);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_13);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_14.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_14);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_15);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                            <span class=""clock-button"">
                                                <img src=""/assets/clock-blue.png"">
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class=""right-part"">
                                    <p class=""fw-bold"">How long do you need your cleaner to stay?</p>
                                    <div class=""mg-right"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("select", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc030070", async() => {
                    WriteLiteral("\r\n                                            ");
                    __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc030383", async() => {
                        WriteLiteral("3.0 Hrs");
                    }
                    );
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                    __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                    BeginWriteTagHelperAttribute();
                    __tagHelperStringValueBuffer = EndWriteTagHelperAttribute();
                    __tagHelperExecutionContext.AddHtmlAttribute("selected", Html.Raw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_16.Value;
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_16);
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
                    {
                        await __tagHelperExecutionContext.SetOutputContentAsync();
                    }
                    Write(__tagHelperExecutionContext.Output);
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
                    WriteLiteral("\r\n\r\n                                            ");
                    __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc032057", async() => {
                        WriteLiteral("4.0 Hrs");
                    }
                    );
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                    __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_17.Value;
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_17);
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
                    {
                        await __tagHelperExecutionContext.SetOutputContentAsync();
                    }
                    Write(__tagHelperExecutionContext.Output);
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
                    WriteLiteral("\r\n\r\n                                            ");
                    __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc033396", async() => {
                        WriteLiteral("5.0 Hrs");
                    }
                    );
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                    __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_18.Value;
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_18);
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
                    {
                        await __tagHelperExecutionContext.SetOutputContentAsync();
                    }
                    Write(__tagHelperExecutionContext.Output);
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
                    WriteLiteral("\r\n\r\n                                            ");
                    __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc034735", async() => {
                        WriteLiteral("6.0 Hrs");
                    }
                    );
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
                    __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
                    __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper.Value = (string)__tagHelperAttribute_19.Value;
                    __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_19);
                    await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                    if (!__tagHelperExecutionContext.Output.IsContentModified)
                    {
                        await __tagHelperExecutionContext.SetOutputContentAsync();
                    }
                    Write(__tagHelperExecutionContext.Output);
                    __tagHelperExecutionContext = __tagHelperScopeManager.End();
                    WriteLiteral("\r\n\r\n\r\n                                        ");
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.SelectTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper);
#nullable restore
#line 98 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.servicehours);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_SelectTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_20);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_21);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                            </div>

                            <hr>

                            <p class=""mt-5 fw-bold"">Extra services</p>
                            <div class=""extra-service-book d-flex flex-wrap"">
                                <div class=""extra-items-book text-center"">
                                    <div id=""extra-ser-1"" class=""extra-img d-flex justify-content-center align-items-center mx-auto"">
                                        <img id=""sr-1"" src=""/assets/3.png""");
                BeginWriteAttribute("alt", " alt=\"", 6980, "\"", 6986, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                    </div>
                                    <div class=""extra-details mt-3"">
                                        <p class=""extra-title mb-0"">
                                            Inside cabinets
                                        </p>
                                    </div>
                                    <div class=""fade"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc038749", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 127 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.extraSer1);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_23);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                                <div class=""extra-items-book text-center"">
                                    <div id=""extra-ser-2"" class=""extra-img d-flex justify-content-center align-items-center mx-auto"">
                                        <img id=""sr-2"" src=""/assets/5.png""");
                BeginWriteAttribute("alt", " alt=\"", 7882, "\"", 7888, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                    </div>
                                    <div class=""extra-details mt-3"">
                                        <p class=""extra-title mb-0"">
                                            Inside fridge
                                        </p>
                                    </div>
                                    <div class=""fade"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc041535", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 140 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.extraSer2);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_24);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                                <div class=""extra-items-book text-center"">
                                    <div id=""extra-ser-3"" class=""extra-img d-flex justify-content-center align-items-center mx-auto"">
                                        <img id=""sr-3"" src=""/assets/4.png""");
                BeginWriteAttribute("alt", " alt=\"", 8782, "\"", 8788, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                    </div>
                                    <div class=""extra-details mt-3"">
                                        <p class=""extra-title mb-0"">
                                            Inside oven
                                        </p>
                                    </div>
                                    <div class=""fade"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc044319", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 153 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.extraSer3);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_25);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                                <div class=""extra-items-book text-center"">
                                    <div id=""extra-ser-4"" class=""extra-img d-flex justify-content-center align-items-center mx-auto"">
                                        <img id=""sr-4"" src=""/assets/2.png""");
                BeginWriteAttribute("alt", " alt=\"", 9680, "\"", 9686, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                    </div>
                                    <div class=""extra-details mt-3"">
                                        <p class=""extra-title mb-0"">
                                            Laundry wash & dry
                                        </p>
                                    </div>
                                    <div class=""fade"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc047110", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 166 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.extraSer4);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_26);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                                <div class=""extra-items-book text-center"">
                                    <div id=""extra-ser-5"" class=""extra-img d-flex justify-content-center align-items-center mx-auto"">
                                        <img id=""sr-5"" src=""/assets/1.png""");
                BeginWriteAttribute("alt", " alt=\"", 10585, "\"", 10591, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                    </div>
                                    <div class=""extra-details mt-3"">
                                        <p class=""extra-title mb-0"">
                                            Interior windows
                                        </p>
                                    </div>
                                    <div class=""fade"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc049901", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 179 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.extraSer5);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_27);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <p class=""mt-5 fw-bold"">Comments</p>
                            <div>
                                ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("textarea", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "556642273f543793f972f34b8339c28f5b3a0dc052008", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_TextAreaTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.TextAreaTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_TextAreaTagHelper);
#nullable restore
#line 186 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_TextAreaTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.comments);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_TextAreaTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_28);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_29);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                            </div>\r\n                            <div class=\"mt-3 input-group\">\r\n                                ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "556642273f543793f972f34b8339c28f5b3a0dc053941", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
#nullable restore
#line 189 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.ServiceRequestViewModel.haspets);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_30);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_31);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                <label class=""check_label"">I have pets at Home</label>
                            </div>

                            <hr>
                            <div class=""bt book1"">
                                <button class=""c_sub_btn continue-1"" type=""button"" name=""continue""><h3>Continue</h3></button>
                            </div>
                        </div>
                        <div class=""fade ss_step_3"">
                            <div class=""bathsec"">
                                <p class=""fw-bold"">Please enter your address so that your helper can find you.</p>
                                <div class=""pt-2 cust_addresses"">
");
#nullable restore
#line 202 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                      
                                        if (Model != null)
                                        {
                                            foreach (var data in Model.address)
                                            {

#line default
#line hidden
#nullable disable
                WriteLiteral(@"                                                <div class=""row ss_address_radio"" id=""add1"">
                                                    <div class=""col-md-1 text-center"">
                                                        <input class=""radio_address form-check-input""");
                BeginWriteAttribute("id", " id=\"", 12988, "\"", 13001, 1);
#nullable restore
#line 209 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
WriteAttributeValue("", 12993, data.id, 12993, 8, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                WriteLiteral(@" name=""ss_address"" type=""radio"" />
                                                    </div>
                                                    <div class=""col-md-7 align-items-center"">
                                                        <div class=""row pt-2"">
                                                            <div class=""col-sm-12 d-flex"">
                                                                <label>Address : </label>
                                                                <pre class=""ss_aaddress_street""> ");
#nullable restore
#line 215 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                                                                            Write(data.addressline1);

#line default
#line hidden
#nullable disable
                WriteLiteral(" </pre>\r\n                                                                <pre>,</pre>\r\n                                                                <pre class=\"ss_address_city\">");
#nullable restore
#line 217 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                                                                        Write(data.city);

#line default
#line hidden
#nullable disable
                WriteLiteral("</pre>\r\n                                                                <pre class=\"ss_address_pin\">");
#nullable restore
#line 218 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                                                                       Write(data.postalcode);

#line default
#line hidden
#nullable disable
                WriteLiteral(@"</pre>
                                                            </div>
                                                        </div>
                                                        <div class=""row"">
                                                            <div class=""col-sm-12 d-flex"">
                                                                <label>Phonenumber : </label>
                                                                <p class=""ss_address_phone"">");
#nullable restore
#line 224 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                                                                       Write(data.phonenumber);

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n                                                            </div>\r\n                                                        </div>\r\n                                                    </div>\r\n                                                </div>\r\n");
#nullable restore
#line 229 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
                                            }
                                        }
                                    

#line default
#line hidden
#nullable disable
                WriteLiteral("\r\n                                    <div>\r\n                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.SelfClosing, "556642273f543793f972f34b8339c28f5b3a0dc060955", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 234 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.addressId);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_32);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_33.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_33);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                </div>

                                <div class=""col-lg-1"">
                                    <button class=""newadd_btn mb-3 mt-2"" type=""button"" name=""newadd"">+ Add New Address</button>
                                </div>
                                <div class=""new_add fade"">
                                    <div class=""row"">
                                        <div class=""col-md-6"">
                                            <p class=""mb-1"">Street</p>
                                            <input id=""add_street"" type=""text"" name=""Street"" class=""form-control"" placeholder=""Street"">
                                            <div id=""add_street_err"" class=""text-danger fade"">
                                                streetname required
                                            </div>
                                        </div>
                                        <div class=""col-md");
                WriteLiteral(@"-6"">
                                            <p class=""mb-1"">House Number</p>
                                            <input id=""add_house"" type=""text"" placeholder=""House number"" class=""form-control"" name=""houseno"" onkeypress=""return (event.charCode !=8 && event.charCode ==0 || ( event.charCode == 46 || (event.charCode >= 48 && event.charCode <= 57)))"" />
                                            <div id=""add_house_err"" class=""text-danger fade"">
                                                House number required
                                            </div>
                                        </div>
                                        <div class=""col-md-6"">
                                            <p class=""mt-3 mb-1"">Postcode</p>
                                            <input id=""add_postal"" type=""text"" placeholder=""Postalcode"" class=""form-control"" name=""postal"" onkeypress=""return (event.charCode !=8 && event.charCode ==0 || ( event.charCode == 46 || (event.charCode >");
                WriteLiteral(@"= 48 && event.charCode <= 57)))"" />

                                        </div>
                                        <div class=""col-md-6"">
                                            <p class=""mt-3 mb-1"">City</p>
                                            <input id=""add_city"" type=""text"" placeholder=""City"" class=""form-control"" name=""cityname"" />
                                            <div id=""add_city_err"" class=""text-danger fade"">
                                                city name required
                                            </div>
                                        </div>
                                        <div class=""col-md-6"">
                                            <p class=""mt-3 mb-1"">Phone Number</p>
                                            <div class=""row g-0"">
                                                <div class=""col-sm-12 input-group"">
                                                    <span class=""c_code align-items-center justify-c");
                WriteLiteral(@"ontent-center"">+49</span>
                                                    <input id=""add_mobile"" type=""tel"" name=""Phonenumber"" class=""form-control"" placeholder=""Mobile Number"" pattern=""[0-9]{10}"" onkeypress=""return (event.charCode !=8 && event.charCode ==0 || ( event.charCode == 46 || (event.charCode >= 48 && event.charCode <= 57)))"">
                                                </div>
                                                <div id=""add_mobile_err"" class=""text-danger fade"">
                                                    phonenumber required
                                                </div>
                                            </div>
                                        </div>
                                        <div class=""row"">
                                            <div class=""mt-3 col-lg-12 col-md-12 col-sm-12"">
                                                <button class=""b_save_btn"" type=""submit"" name=""Save"">Save</button>
                          ");
                WriteLiteral(@"                      <button class=""b_discard_btn"" type=""submit"" name=""Discard"">Discard</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                                <hr>

                                <div class=""row pt-2"">
                                    <label>Your Favourite Service Providers</label>
                                </div>

                                <hr>

                                <div class=""row pt-1"">
                                    <label>You can choose your favourite service provider from below list</label>
                                </div>
                                <div class=""row pt-2"">
                                    <div class=""col-md-3 justify-content-center"">
                                        <div class="" justify-content-center text-center"">
                                 ");
                WriteLiteral("           <div class=\"extra-img-sp-avatar d-flex justify-content-center align-items-center mx-auto\">\r\n                                                <img src=\"/assets/avatar-hat.png\"");
                BeginWriteAttribute("alt", " alt=\"", 20221, "\"", 20227, 0);
                EndWriteAttribute();
                WriteLiteral(@">
                                            </div>
                                            <div class=""extra-details text-center mt-3"">
                                                <p class=""extra-sp-name mb-0"">
                                                    Sandip Patel
                                                </p>
                                                <button class=""sp_select_btn"">select</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <hr>
                                <div class=""bt book1"">
                                    <button class=""c_sub_btn continue-2"" type=""button"" name=""continue""><h3>Continue</h3></button>
                                </div>
                            </div>
                        </div>
                        <div class=""fade ss_step_4"">
           ");
                WriteLiteral(@"                 <div class=""bathsec"">
                                <p class=""fw-bold"">Pay securely with Helperland payment gateway.</p>
                                <hr>
                                <div class=""row pt-2"">
                                    <div class=""col-lg-12"">
                                        <iframe name=""__privateStripeFrame52510"" frameborder=""0"" allowtransparency=""true""
                                                scrolling=""no"" allow=""payment *""
                                                src=""https://js.stripe.com/v3/elements-inner-card-6f95dd34a5c89aae610bcf619d0b2112.html#locale=en&amp;wait=false&amp;mids[guid]=26be9e97-86fa-42b9-a15e-5580bc4b93c6697bcd&amp;mids[muid]=b9c63c2a-e1e3-4391-af0e-035491e42cff6f2065&amp;mids[sid]=50a9fbe1-5a7d-44fa-bb11-fabf27d5d426d48d0d&amp;hidePostalCode=true&amp;style[base][iconColor]=%23666EE8&amp;style[base][color]=%2331325F&amp;style[base][lineHeight]=36px&amp;style[base][fontSize]=16px&amp;style[base][::placeholder]");
                WriteLiteral(@"[color]=%23c5c5c5&amp;rtl=false&amp;componentName=card&amp;keyMode=test&amp;apiKey=pk_test_CbN2mTsadzVC1WpDPDgcDWbG&amp;referrer=https%3A%2F%2Fweb1.anasource.com%2Ftrainee2021%2Fbook-service&amp;controllerId=__privateStripeController5256""
                                                title=""Secure card payment input frame""
                                                style="" margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; transform: translate(0px) !important; height: 36px;"">
                                        </iframe>
                                    </div>
                                </div>
                                <hr>
                                <div class=""row pt-2"">
                                    <div class=""col-md-9"">
                                    </div>
                                    <div class=""col-md-3"">
     ");
                WriteLiteral(@"                                   <div class=""row"">
                                            <label class=""accepted_card_lbl"">Accepted cards</label>
                                        </div>
                                        <div class=""row d-flex"">

                                            <img class=""card_img"" src=""/assets/visa-1.png"">
                                            <img class=""card_img"" src=""/assets/master-2.png"">
                                            <img class=""card_img"" src=""/assets/ax-1.png"">

                                        </div>
                                    </div>
                                </div>
                                <hr>

                                <div class=""row pt-2 accept_3_policy"">
                                    <div class=""col-md-1 pt-1"">
                                        ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "556642273f543793f972f34b8339c28f5b3a0dc072676", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_22.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_22);
#nullable restore
#line 359 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.checkPolicy);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_34);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_31);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                                    </div>
                                    <div class=""col-md-11"">
                                        <label class=""check_label_book"">I accept <a href=""#"">terms and conditions </a>, the <a href=""#"">Cancellation Policy </a> and the <a href=""#""> privacy policy</a>. I confirm that Helperland starts to execute the contract before the expiry of the withdrawal period and I loose my right of withdrawal as a consumer with full performance of the contract. </label>
                                    </div>
                                </div>

                                <hr>

                                <div class=""bt book1"">
                                    <button class=""pay_btn"" type=""submit"" name=""BookWC""><h3>Complete Booking</h3></button>
                                </div>
                            </div>
                        </div>
                    ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Action = (string)__tagHelperAttribute_35.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_35);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Controller = (string)__tagHelperAttribute_6.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
                </div>
            </div>

            <div class=""col-lg-4"">
                <div class=""row ss_pay_summary"">
                    <label>Payment Summary</label>
                </div>
                <div class=""row ps_container justify-content-center"">
                    <div class=""row pt-4 ps_p_tag"">
                        <div class=""d-flex"">
                            <p class=""ps_date"">01/01/1111</p>
                            <pre>  ''  </pre>
                            <p class=""ps_time"">00:00</p>
                            <p class=""ps_time_meredian"">PM</p>
                        </div>
                    </div>
                    <div class=""row pt-3"">
                        <label>Duration</label>
                    </div>

                    <div class=""row pt-1 ps_p_tag"">
                        <div class=""col-sm-3"">
                            <p>Basic</p>
                        </div>
                        <div class=""col-sm-6"">
      ");
            WriteLiteral(@"                  </div>
                        <div class=""col-sm-3 d-flex"">
                            <p class=""ps_basic_hr ms-auto"">3</p>
                            <pre> hrs</pre>
                        </div>
                    </div>
                    <div class=""row pt-1 ps_p_tag ps_ser_1 fade"">
                        <div class=""col-sm-7"">
                            <p>Inside Cabinets (extra)</p>
                        </div>
                        <div class=""col-sm-2"">

                        </div>
                        <div class=""col-sm-3 pr-0 d-flex "">
                            <p class=""ps_extra_min ms-auto"">30</p>
                            <pre> min</pre>
                        </div>
                    </div>
                    <div class=""row pt-1 ps_p_tag ps_ser_2 fade"">
                        <div class=""col-sm-7"">
                            <p>Inside Fridge (extra)</p>
                        </div>
                        <div class=""col-sm-2");
            WriteLiteral(@""">

                        </div>
                        <div class=""col-sm-3 pr-0 d-flex "">
                            <p class=""ps_extra_min ms-auto"">30</p>
                            <pre> min</pre>
                        </div>
                    </div>
                    <div class=""row pt-1 ps_p_tag ps_ser_3 fade"">
                        <div class=""col-sm-7"">
                            <p>Inside Oven (extra)</p>
                        </div>
                        <div class=""col-sm-2"">

                        </div>
                        <div class=""col-sm-3 pr-0 d-flex "">
                            <p class=""ps_extra_min ms-auto"">30</p>
                            <pre> min</pre>
                        </div>
                    </div>
                    <div class=""row pt-1 ps_p_tag ps_ser_4 fade"">
                        <div class=""col-sm-8"">
                            <p>Laundry Wash & dry (extra)</p>
                        </div>
                       ");
            WriteLiteral(@" <div class=""col-sm-1"">

                        </div>
                        <div class=""col-sm-3 pr-0 d-flex "">
                            <p class=""ps_extra_min ms-auto"">30</p>
                            <pre> min</pre>
                        </div>
                    </div>
                    <div class=""row pt-1 ps_p_tag ps_ser_5 fade"">
                        <div class=""col-sm-7"">
                            <p>Interior Windows (extra)</p>
                        </div>
                        <div class=""col-sm-2"">

                        </div>
                        <div class=""col-sm-3 pr-0 d-flex "">
                            <p class=""ps_extra_min ms-auto"">30</p>
                            <pre> min</pre>
                        </div>
                    </div>
                    <div class=""row pt-1"">
                        <hr class=""seperator"">
                    </div>
                    <div class=""row pt-1"">
                        <div class=""col-sm-");
            WriteLiteral(@"6"">
                            <label>Total Service Time</label>
                        </div>
                        <div class=""col-sm-3"">

                        </div>
                        <div class=""col-sm-3 d-flex"">
                            <label class=""ps_total_time ms-auto"">3</label>
                            <pre><label> hrs</label></pre>
                        </div>
                    </div>
                    <div class=""row pt-3"">
                        <hr class=""seperator"">
                    </div>
                    <div class=""row pt-2 ps_p_tag"">
                        <div class=""col-sm-6"">
                            <p>Per Cleaning</p>
                        </div>
                        <div class=""col-sm-3"">

                        </div>
                        <div class=""col-sm-3 d-flex"">
                            <p class=""ps_per_clean ms-auto"">60 €</p>
                        </div>
                    </div>
                    <d");
            WriteLiteral(@"iv class=""row pt-2"">
                        <hr class=""seperator"">
                    </div>
                    <div class=""row pt-2"">
                        <div class=""col-sm-6"">
                            <p class=""ps_total_payment"">Total Payment</p>
                        </div>
                        <div class=""col-sm-6 d-flex"">
                            <p class=""ps_total_price ms-auto"">60</p>
                            <p class=""ps_grand_total"">€</p>
                        </div>
                    </div>
                    <div class=""row pt-2 ps_footer"">
                        <div class=""col-sm-1 "">
                            <img src=""/assets/smiley.png"" alt=""smiley"">
                        </div>
                        <div class=""col-sm-11"">
                            <p class=""ps_footer_lbl"">See what is always included</p>
                        </div>
                    </div>
                </div>
                <div class=""row pt-3 ss_question_sect""");
            WriteLiteral(@">
                    <div class=""row"">
                        <div class=""col-sm-12 text-center"">
                            <label class=""question_lbl"">Questions?</label>
                        </div>
                    </div>
                    <div class=""row pt-2"">
                        <div class=""col-sm-12 accordion"" id=""accordionone"">
                            <div class=""row mb-2 accordion_item"">
                                <h2 class=""accordion-header accordion_btn collapsed"" data-bs-toggle=""collapse""
                                    data-bs-target=""#fc-1"">
                                    <img src=""/assets/right-arrow-dark.png""");
            BeginWriteAttribute("class", " class=\"", 32047, "\"", 32055, 0);
            EndWriteAttribute();
            WriteLiteral(@" alt=""right-arrow-dark"">
                                    What's included in a cleaning?
                                </h2>
                                <div id=""fc-1"" class=""accordion-collapse collapse"" data-bs-parent=""#accordionone"">
                                    <div class=""accordion-body"">
                                        <p>Bedroom, Living Room & Common Areas, Bathrooms, Kitchen, Extras </p>
                                    </div>
                                </div>
                            </div>
                            <div class=""row pt-1"">
                                <hr class=""seperator"">
                            </div>
                            <div class=""row pt-1 mb-2 accordion_item"">
                                <h2 class=""accordion-header accordion_btn collapsed"" data-bs-toggle=""collapse""
                                    data-bs-target=""#fc-2"">
                                    <img src=""/assets/right-arrow-dark.png""");
            BeginWriteAttribute("class", " class=\"", 33068, "\"", 33076, 0);
            EndWriteAttribute();
            WriteLiteral(@" alt=""right-arrow-dark"">
                                    Which Helperland professional will come to my place?
                                </h2>
                                <div id=""fc-2"" class=""accordion-collapse collapse"" data-bs-parent=""#accordionone"">
                                    <div class=""accordion-body"">
                                        <p>Helperland has a vast network of experienced, top-rated cleaners. Based on the time and date of your request, we work to assign the best professional available. Like working with a specific pro? Add them to your Pro Team from the mobile app and they'll be requested first for all future bookings. You will receive an email with details about your professional prior to your appointment.</p>
                                    </div>
                                </div>
                            </div>
                            <div class=""row pt-1"">
                                <hr class=""seperator"">
                        ");
            WriteLiteral(@"    </div>
                            <div class=""row pt-1 mb-2 accordion_item"">
                                <h2 class=""accordion-header accordion_btn collapsed"" data-bs-toggle=""collapse""
                                    data-bs-target=""#fc-3"">
                                    <img src=""/assets/right-arrow-dark.png""");
            BeginWriteAttribute("class", " class=\"", 34433, "\"", 34441, 0);
            EndWriteAttribute();
            WriteLiteral(@" alt=""right-arrow-dark"">
                                    Can I skip or reschedule bookings?
                                </h2>
                                <div id=""fc-3"" class=""accordion-collapse collapse"" data-bs-parent=""#accordionone"">
                                    <div class=""accordion-body"">
                                        <p>You can reschedule any booking for free at least 24 hours in advance of the scheduled start time. If you need to skip a booking within the minimum commitment, we’ll credit the value of the booking to your account. You can use this credit on future cleanings and other Helperland services.</p>
                                    </div>
                                </div>
                            </div>
                            <div class=""row pt-1"">
                                <hr class=""seperator"">
                            </div>
                            <div class=""row pt-1"">
                                <a href=""#"" class=""f");
            WriteLiteral(@"or_more_help"">For more help</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class=""our-news-letter"">
    <div class=""container text-center"">

        <h2 class=""news-letter"">GET OUR NEWSLETTER</h2>
        <div class=""form-row d-flex justify-content-center align-items-center"">
            <div class=""form-group"">
                <label for=""email"" style=""display: none;"">YOUR EMAIL</label>
                <input type=""text"" placeholder=""YOUR EMAIL"" id=""email"" class=""form-control email"">
            </div>
            <div class=""btn-wrapper"">
                <button type=""submit"" class=""red-btn"">Submit</button>
            </div>
        </div>
    </div>
</section>

");
#nullable restore
#line 594 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\BookService.cshtml"
 if(ViewBag.bookservice != null)
{
    //document.getElementById('pills-Schedule-Plan-tab').setAttribute("data-bs-toggle", "pill");
    //document.getElementById('pills-Setup-Service-tab').classList.add('done');
    //document.getElementById('pills-Setup-Service-tab').classList.remove('active');
    //document.getElementById('pills-Schedule-Plan-tab').classList.add('active');
    //document.getElementById('pills-Setup').classList.remove('show');
    //document.getElementById('pills-Setup').classList.remove('active');
    //document.getElementById('pills-Schedule-Plan').classList.add('show');
    //document.getElementById('pills-Schedule-Plan').classList.add('active');

}

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n\r\n\r\n\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Helperland.viewmodel.BookServiceViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
