#pragma checksum "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e87ba5784ae981a0a132c864e206d0b9856e1735"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland.viewmodel;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\_ViewImports.cshtml"
using Helperland.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e87ba5784ae981a0a132c864e206d0b9856e1735", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"7058251e67477ed81f1fbef7512c03f3605d1a08", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<Helperland.viewmodel.LoginViewModel>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "email", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("login-form form-control"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("id", new global::Microsoft.AspNetCore.Html.HtmlString("pwd"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("placeholder", new global::Microsoft.AspNetCore.Html.HtmlString("Email"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_4 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("name", "email", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_5 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("text-danger"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_6 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("type", "password", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_7 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("placeholder", new global::Microsoft.AspNetCore.Html.HtmlString("Password"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_8 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("name", "password", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_9 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Login", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_10 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Home", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_11 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Register", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_12 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("ms-1"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.ValidationMessageTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml"
  
    ViewData["Title"] = "Index1";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";

#line default
#line hidden
#nullable disable
            WriteLiteral(@"<!--login modal-->
<div class=""modal fade"" id=""staticBackdrop"" data-bs-backdrop=""static"" data-bs-keyboard=""false"" tabindex=""-1""
     aria-labelledby=""staticBackdropLable"" aria-hidden=""true"">
    <div class=""modal-dialog modal-dialog-centered"" role=""document"">
        <div class=""modal-content"">
            <div class=""modal-body"">
                <h4 class=""logHeader ms-3"">Login to your account</h4>
                <button type=""button"" class=""close"" data-bs-dismiss=""modal"" aria-label=""Close"">
                    <img src=""/assets/close.png"">
                </button>
            </div>
            ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e87ba5784ae981a0a132c864e206d0b9856e17358909", async() => {
                WriteLiteral("\r\n                <div class=\"form-log mb-3 mt-3\">\r\n                    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "e87ba5784ae981a0a132c864e206d0b9856e17359241", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 19 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.Email);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_0.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_3);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.Name = (string)__tagHelperAttribute_4.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_4);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("span", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e87ba5784ae981a0a132c864e206d0b9856e173511423", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.ValidationMessageTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper);
#nullable restore
#line 20 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.Email);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-validation-for", __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                    <img src=\"/assets/user_1.png\" class=\"logImg\">\r\n                </div>\r\n                <div class=\"form-log mb-3\">\r\n                    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("input", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagOnly, "e87ba5784ae981a0a132c864e206d0b9856e173513232", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.InputTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper);
#nullable restore
#line 24 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.Password);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-for", __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.InputTypeName = (string)__tagHelperAttribute_6.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_6);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_1);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_7);
                __Microsoft_AspNetCore_Mvc_TagHelpers_InputTagHelper.Name = (string)__tagHelperAttribute_8.Value;
                __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_8);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral("\r\n                    ");
                __tagHelperExecutionContext = __tagHelperScopeManager.Begin("span", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e87ba5784ae981a0a132c864e206d0b9856e173515418", async() => {
                }
                );
                __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.ValidationMessageTagHelper>();
                __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper);
#nullable restore
#line 25 "C:\Users\Asus\source\repos\Helperland\Helperland\Views\Home\Index.cshtml"
__Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper.For = ModelExpressionProvider.CreateModelExpression(ViewData, __model => __model.Password);

#line default
#line hidden
#nullable disable
                __tagHelperExecutionContext.AddTagHelperAttribute("asp-validation-for", __Microsoft_AspNetCore_Mvc_TagHelpers_ValidationMessageTagHelper.For, global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
                __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_5);
                await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
                if (!__tagHelperExecutionContext.Output.IsContentModified)
                {
                    await __tagHelperExecutionContext.SetOutputContentAsync();
                }
                Write(__tagHelperExecutionContext.Output);
                __tagHelperExecutionContext = __tagHelperScopeManager.End();
                WriteLiteral(@"
                    <img src=""/assets/lock.png"" class=""logImg1"">
                </div>
                <div class=""form-log mb-3"">
                    <input type=""checkbox"" value=""isRemeberMe"" id=""rememberMe"">
                    <label for=""rememberMe"">Remember me</label>
                </div>
                <div class=""form-log mb-3"">
                    <button type=""submit"" class=""loginBtn"">Login</button>
                </div>
            ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Action = (string)__tagHelperAttribute_9.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_9);
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper.Controller = (string)__tagHelperAttribute_10.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_10);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
            <div class=""text_center mb-1"">
                <a href=""#"" data-bs-dismiss=""modal"" data-bs-toggle=""modal"" data-bs-target=""#ForgetModal"">
                    Forget
                    Password?
                </a>
            </div>
            <div class=""text_center"">
                Don't have an account?");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "e87ba5784ae981a0a132c864e206d0b9856e173519261", async() => {
                WriteLiteral("\r\n                    Create an\r\n                    <br>account\r\n                ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_11.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_11);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_10.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_10);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_12);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral(@"
            </div>
        </div>
    </div>
</div>
<section class=""about"">

    <h2 class=""why-helperland"">Why Helperland</h2>
    <div id=""card"">
        <div class=""container"">
            <div class=""row"">
                <div class=""col-md-4"">
                    <img src=""/assets/helper-img-1.png"" style=""height: 330px;"">
                    <h2 class=""card-text"">
                        Experience & Vetted<br>
                        Professionals
                    </h2>
                    <p>
                        dominate the industry in scale and scope<br>with an adaptable, extensive network that<br>consistently
                        delivers exceptional results.
                    </p>
                </div>
                <div class=""col-md-4"">
                    <img src=""/assets/group-23.png"" style=""height: 330px;"">
                    <h2 class=""card-text1"">Secure Online Payment</h2>
                    <p>
                        Payment is processed securel");
            WriteLiteral(@"y online.<br> Customers pay safely online and<br>
                        manage the booking.
                    </p>
                </div>
                <div class=""col-md-4"">
                    <img src=""/assets/group-24.png"" style=""height: 330px;"">
                    <h2 class=""card-text"">
                        Dedicated Customer<br>
                        Service
                    </h2>
                    <p>
                        to our customers and are guided in all we do<br> by their needs. The team is always happy to<br> support
                        you and offer all the information.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class=""blog-section"">
    <div class=""max-width"" style=""display:flex; flex-wrap: wrap;"">

        <div class=""data"">
            <h2>
                Lorem ipsum dolor sit amet,<br> consectetur
            </h2>
            <p>
                Lorem ipsum dolor sit a");
            WriteLiteral(@"met, consectetur adipiscing elit. Donec nisi sapien, sus-<br>cipit ut accumsan vitae,
                pulvinar ac libero.<br><br>

                Aliquam erat volutpat. Nullam quis ex odio. Nam bibendum cursus purus, vel<br> efficitur urna finibus vitae.
                Nullam finibus aliquet pharetra. Morbi in sem dolor.<br> Integer pretium hendrerit ante quis vehicula.<br><br>

                Mauris consequat ornare enim, sed lobortis quam ultrices sed.
            </p>
        </div>
        <div class=""Ellipse"">
            <img src=""/assets/group-36.png"">
        </div>

    </div>

    <div class=""max-width mb-5"">
        <span>
            <h2 class=""why-helperland"" style=""margin-right:300px"">Our Blog</h2>
        </span>
    </div>

    <div id=""card"">
        <div class=""container"" id=""blog-container"">
            <div class=""row"">
                <div class=""col-md-3 blog-card"">
                    <img class=""Blog"" src=""/assets/group-28.png"">
                    <span cl");
            WriteLiteral(@"ass=""card-text2"">Lorem ipsum dolor sit amet</span>
                    <p class=""date"">January 28, 2019</p>
                    <p class=""card-text3"">
                        Lorem ipsum dolor sit amet, consectetur<br>adipiscing elit. Sed fermentum
                        metus<br>pulvinar aliquet.
                    </p>
                    <div class=""read-more-div"">
                        <a class=""read-more""");
            BeginWriteAttribute("href", " href=\"", 5873, "\"", 5880, 0);
            EndWriteAttribute();
            WriteLiteral(@">Read the post</a>
                        <img class=""arr"" src=""/assets/shape-2.png"">
                    </div>
                </div>
                <div class=""col-md-3 col-sm-6 blog-card"" id=""mid-card"">
                    <img class=""Blog"" src=""/assets/group-29.png"">
                    <span class=""card-text2"">Lorem ipsum dolor sit amet</span>
                    <p class=""date"">January 28, 2019</p>
                    <p class=""card-text3"">
                        Lorem ipsum dolor sit amet, consectetur<br>adipiscing elit. Sed fermentum
                        metus<br>pulvinar aliquet.
                    </p>
                    <div class=""read-more-div"">
                        <a class=""read-more""");
            BeginWriteAttribute("href", " href=\"", 6614, "\"", 6621, 0);
            EndWriteAttribute();
            WriteLiteral(@">Read the post</a>
                        <img class=""arr"" src=""/assets/shape-2.png"">
                    </div>
                </div>
                <div class=""col-md-3 col-sm-6 blog-card"">
                    <img class=""Blog"" src=""/assets/group-30.png"">
                    <span class=""card-text2"">Lorem ipsum dolor sit amet</span>
                    <p class=""date"">January 28, 2019</p>
                    <p class=""card-text3"">
                        Lorem ipsum dolor sit amet, consectetur<br> adipiscing elit. Sed fermentum
                        metus<br>pulvinar aliquet.
                    </p>
                    <div class=""read-more-div"">
                        <a class=""read-more""");
            BeginWriteAttribute("href", " href=\"", 7342, "\"", 7349, 0);
            EndWriteAttribute();
            WriteLiteral(@">Read the post</a>
                        <img class=""arr"" src=""/assets/shape-2.png"">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div style=""background-color: whitesmoke;"">
    <section class=""customer "">

        <div class=""container"">
            <span>
                <h2 class=""testimonial-title"">What Our Customers Say</h2>
            </span>
        </div>

        <div class=""row customer-wrapper d-flex justify-content-center ms-5 me-5"">
            <div class=""col-lg-4 col-sm-6"">
                <div class=""customer-inner"">
                    <em class=""message-infor"">
                        <img src=""/assets/message.png"">
                    </em>
                    <div class=""person-info d-flex align-items-center"">
                        <div class=""person-image"">
                            <img src=""/assets/group-31.png"">
                        </div>
                        <div class=""person-conte");
            WriteLiteral(@"nt"">
                            <span class=""person-name"">Lary Watson</span>
                            <span class=""person-city"">Manchester</span>
                        </div>
                    </div>
                    <div class=""person-detail"">
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed fermentum metus pulvinar aliquet
                            consequat. Praesent nec malesuada nibh.
                        </p>
                        <p>Nullam et metus congue, auctor augue sit amet, consectetur tortor.</p>
                        <a");
            BeginWriteAttribute("href", " href=\"", 9012, "\"", 9019, 0);
            EndWriteAttribute();
            WriteLiteral(@" title=""Read More"" class=""arrow-link"">Read More <em><img src=""/assets/shape-2.png""></em></a>
                    </div>
                </div>
            </div>
            <div class=""col-lg-4 col-sm-6"">
                <div class=""customer-inner"">
                    <em class=""message-infor"">
                        <img src=""/assets/message.png"">
                    </em>
                    <div class=""person-info d-flex align-items-center"">
                        <div class=""person-image"">
                            <img src=""/assets/group-32.png"">
                        </div>
                        <div class=""person-content"">
                            <span class=""person-name"">John Smith</span>
                            <span class=""person-city"">Manchester</span>
                        </div>
                    </div>
                    <div class=""person-detail"">
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipiscing");
            WriteLiteral(@" elit. Sed fermentum metus pulvinar aliquet
                            consequat. Praesent nec malesuada nibh.
                        </p>
                        <p>Nullam et metus congue, auctor augue sit amet, consectetur tortor.</p>
                        <a");
            BeginWriteAttribute("href", " href=\"", 10313, "\"", 10320, 0);
            EndWriteAttribute();
            WriteLiteral(@" title=""Read More"" class=""arrow-link"">Read More <em><img src=""/assets/shape-2.png""></em></a>
                    </div>
                </div>
            </div>
            <div class=""col-lg-4 col-sm-6"">
                <div class=""customer-inner"">
                    <em class=""message-infor"">
                        <img src=""/assets/message.png"">
                    </em>
                    <div class=""person-info d-flex align-items-center"">
                        <div class=""person-image"">
                            <img src=""/assets/group-33.png"">
                        </div>
                        <div class=""person-content"">
                            <span class=""person-name"">Lars Johnson</span>
                            <span class=""person-city"">Manchester</span>
                        </div>
                    </div>
                    <div class=""person-detail"">
                        <p>
                            Lorem ipsum dolor sit amet, consectetur adipisci");
            WriteLiteral(@"ng elit. Sed fermentum metus pulvinar aliquet
                            consequat. Praesent nec malesuada nibh.
                        </p>
                        <p>Nullam et metus congue, auctor augue sit amet, consectetur tortor.</p>
                        <a");
            BeginWriteAttribute("href", " href=\"", 11616, "\"", 11623, 0);
            EndWriteAttribute();
            WriteLiteral(@" title=""Read More"" class=""arrow-link"">Read More <em><img src=""/assets/shape-2.png""></em></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class=""news-letter"">
        <div class=""container text-center"">
            <a");
            BeginWriteAttribute("href", " href=\"", 11916, "\"", 11923, 0);
            EndWriteAttribute();
            WriteLiteral(" class=\"scroll-top\" style=\"display: inline-block;\"><img src=\"/assets/forma-1.png\"></a>\r\n            <a");
            BeginWriteAttribute("href", " href=\"", 12026, "\"", 12033, 0);
            EndWriteAttribute();
            WriteLiteral(@" class=""message-boat"" style=""display: inline-block;""><img src=""/assets/layer-598.png""></a>
            <h3 class=""heading"">GET OUR NEWSLETTER</h3>
            <div id=""container"">
                <div class=""buttons"">

                    <div class=""email"">
                        <input type=""text"" placeholder=""   YOUR EMAIL"" style=""background-color:white; border-radius: 50px; padding: 5px 10px;"">
                        <button style=""background-color: lightsalmon; border-radius: 50px; color: white; border-color: lightsalmon; padding:5px 15px"">Submit</button>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div>

");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<Helperland.viewmodel.LoginViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
